name: Auto-Deploy

on: push # TODO: push on directory

jobs:
  auto-deploy:
    name: Auto deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout pages
        uses: actions/checkout@v2
        with:
          repository: 'another-s347/another-s347.github.io'
          path: 'pages'
      
      - name: ls
        run: ls

      - name: Install hexo
        run: npm install hexo-cli

      - name: Npm install
        run: npm install
        working-directory: ./hexo
      
      - name: Generate
        run: ./node_modules/.bin/hexo g
        working-directory: ./hexo

      - name: Copy
        run: cp -r ./hexo/public ./pages/blogs

      - name: Push
        run: git push -u origin main
        working-directory: pages